server.port: 8088

spring:
  application:
    name: oauth_sso
  datasource:
    url: jdbc:mysql://localhost:3306/sso
    username: sso
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

  profiles:
    active: oauth2

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: f615cad632805f0b9d40f13b8f59d9a1
            client-secret: z7WidG5vtZE0BSuVVvPGBLjSYEdgcCP0
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8088/api/v1/oauth2/kakao
            client-authentication-method: POST
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id


  logging:
    level:
      root: debug